[package]
name = "xor_name"
version = "0.9.2"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Xor Type"
homepage = "http://maidsafe.net"
edition = "2018"
license = "MIT OR BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/maidsafe/xor-name"

[dependencies]
rand = "~0.7.3"
num-bigint = "~0.3.0"
hex = "~0.2.0"
bincode = "1.2.1"
serde = { version = "1.0.113", features = ["derive"] }
log = "~0.4.8"
hex_fmt = "~0.1.0"

