[package]
name = "xor_name"
version = "0.1.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Type with xor methods"
documentation = "http://maidsafe.net/xor_name/latest"
repository = "https://github.com/maidsafe/xor_name"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"
edition = "2018"

[dependencies]
rustc-serialize = "~0.3.24"
rand = "0.7.3"
num-bigint = "~0.3.0"
rand_core = "~0.5.1"
hex = "~0.2.0"
rand_os = "~0.2.2"
bincode = "1.2.1"
serde = { version = "1.0.113", features = ["derive"] }
log = "0.4.8"
hex_fmt = "0.1.0"
rand_xorshift = "0.2.0"

